apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: service-account
      containers:
        - name: frontend-container
          image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: secret
          resources:
            requests:
                memory: "64Mi" 
                cpu: "250m"  
            limits:
                memory: "128Mi"
                cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          
