apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: first-namespace
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
