# Generated by Django 5.0 on 2024-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('worker_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
