# Generated by Django 5.0 on 2024-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workers_address_workers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
