# Generated by Django 5.0 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workers_address_alter_workers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='workers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='address',
            field=models.CharField(default='Elad', max_length=30),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(default='empty@empty.com', max_length=254),
        ),
    ]
