# Generated by Django 5.0 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_workers_worker_id_workers_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='id',
        ),
        migrations.AddField(
            model_name='workers',
            name='worker_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
