# Generated by Django 5.0 on 2024-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_remove_workers_id_workers_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='workers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
