# Generated by Django 4.2.6 on 2023-10-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
