# Generated by Django 4.2.6 on 2023-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_user_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.BooleanField(default=True),
        ),
    ]
