# Generated by Django 4.2.6 on 2023-10-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=70)),
                ('prioritize', models.IntegerField()),
                ('target_coordinates_width', models.FloatField()),
                ('target_coordinates_length', models.FloatField()),
                ('enemy_organization', models.CharField(max_length=60)),
                ('purpose_designation', models.CharField(max_length=50)),
                ('target_attacked', models.BooleanField()),
                ('id_target', models.IntegerField()),
            ],
        ),
    ]
