# Generated by Django 4.2.6 on 2023-10-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='id_target',
            new_name='attack_priority',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_coordinates_length',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_coordinates_width',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='purpose_designation',
            new_name='target_goal',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='prioritize',
            new_name='target_id',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_attacked',
            new_name='was_target_destroyed',
        ),
    ]
