# Generated by Django 4.2.6 on 2023-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_id_target_target_attack_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='id',
        ),
        migrations.AlterField(
            model_name='target',
            name='target_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
