# Generated by Django 4.2.4 on 2023-12-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('uploaded_date', models.TimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=15)),
                ('item_category', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=70)),
                ('phon_number', models.IntegerField(max_length=9)),
                ('uploaded_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='users.user')),
            ],
        ),
    ]
