# Generated by Django 4.2.4 on 2023-12-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='taken_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='taken_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
