apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: first-namespace
spec:
  containers:
  - name: backend-container
    image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
    ports:
    - containerPort: 5050