apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: first-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontend-container
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        ports:
        - containerPort: 50