# Generated by Django 4.2.6 on 2023-10-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('date_open', models.DateField(auto_now=True)),
                ('event_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Waiting for Response', 'Waiting for Response'), ('Waiting for Handling', 'Waiting for Handling')], default='Open', max_length=20)),
                ('open_draft', models.BooleanField(default=False)),
                ('sand_archive', models.BooleanField(default=False)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
