# Generated by Django 4.2.6 on 2023-10-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_user_user_user_id'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('upload_date', models.DateField()),
                ('the_file', models.FileField(upload_to='')),
                ('the_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            bases=('files.file',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('text', models.TextField()),
                ('send_date', models.DateField(auto_now=True)),
                ('chat', models.IntegerField()),
                ('the_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            bases=('files.file',),
        ),
    ]
