# Generated by Django 4.2.6 on 2023-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_user_user_user_id'),
        ('files', '0002_share_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_members',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to='users.user'),
        ),
    ]
