# Generated by Django 4.2.6 on 2023-10-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_shared_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='shared_members',
        ),
    ]
