                                                                                                                        # Generated by Django 4.2.6 on 2023-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_user_user_user_id'),
        ('files', '0006_remove_file_shared_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_members',
            field=models.ManyToManyField(related_name='File', to='users.user'),
        ),
    ]
