# Generated by Django 4.2.6 on 2023-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_shared_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='the_file',
        ),
        migrations.AlterField(
            model_name='share',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
