# Generated by Django 4.2.6 on 2023-10-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_user_user_user_id'),
        ('files', '0008_remove_share_the_file_alter_share_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('chat_id', models.IntegerField()),
            ],
            bases=('files.file',),
        ),
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('upload_date', models.DateField(auto_now=True)),
                ('the_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            bases=('files.file',),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.eventchat'),
        ),
    ]
