# Generated by Django 4.2.6 on 2023-10-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_remove_message_file_ptr_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('chat_id', models.IntegerField()),
            ],
            bases=('files.file',),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.eventchat'),
        ),
    ]
