# Generated by Django 4.2.6 on 2023-10-25 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchat',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='files.file'),
        ),
    ]
