# Generated by Django 4.2.6 on 2023-10-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_eventchat_chat_id_alter_eventchat_file_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_close',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file'),
        ),
    ]
