# Generated by Django 4.2.6 on 2023-10-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_file_date_close_alter_eventchat_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='files.eventchat'),
        ),
    ]
