# Generated by Django 4.2.6 on 2023-10-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_unread_messages'),
        ('files', '0021_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='shared_members',
            field=models.ManyToManyField(blank=True, related_name='File', to='users.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='files.eventchat'),
        ),
    ]
