# Generated by Django 4.2.6 on 2023-10-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_file_shared_members_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='File', to='files.eventchat'),
        ),
    ]
