# Generated by Django 4.2.6 on 2023-10-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_alter_eventchat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchat',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
