# Generated by Django 4.2.6 on 2023-10-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_unread_messages'),
        ('files', '0027_alter_eventchat_chat_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='eventchat',
            old_name='file_ptr',
            new_name='event_ptr',
        ),
        migrations.RenameField(
            model_name='eventshare',
            old_name='file_ptr',
            new_name='event_ptr',
        ),
    ]
