# Generated by Django 4.2.6 on 2023-10-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_unread_messages'),
        ('files', '0028_rename_file_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='eventchat',
            old_name='event_ptr',
            new_name='file_ptr',
        ),
        migrations.RenameField(
            model_name='eventshare',
            old_name='event_ptr',
            new_name='file_ptr',
        ),
    ]
