# Generated by Django 4.2.4 on 2023-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=20)),
                ('password', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission', models.IntegerField()),
            ],
        ),
    ]
