# Generated by Django 4.2.4 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
