# Generated by Django 4.2.4 on 2023-12-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taken', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taken',
        ),
    ]
