# Generated by Django 4.2.4 on 2023-12-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_password'),
        ('taken', '0002_delete_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_items', models.CharField(blank=True, max_length=50, null=True)),
                ('taken_date', models.TimeField(auto_now=True)),
                ('return_date', models.TimeField(auto_now=True)),
                ('taken_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_items', to='users.user')),
            ],
        ),
    ]
