# Generated by Django 4.2.4 on 2023-12-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_taken_by'),
        ('taken', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taken',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_items', to='items.items'),
            preserve_default=False,
        ),
    ]
