# Generated by Django 4.2.6 on 2023-10-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='id',
            new_name='people_id',
        ),
    ]
