# Generated by Django 4.2.6 on 2023-10-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_id_people_people_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.people')),
                ('work_place', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('people.people',),
        ),
    ]
