# Generated by Django 4.2.6 on 2023-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(default=[], related_name='Children', to='people.people'),
        ),
    ]
