# Generated by Django 4.2.6 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
