# Generated by Django 4.2.4 on 2023-10-19 13:46

from django.db import migrations, models
from django.db.models.functions import Ceil
from django.db.models import F

def round_up(apps, schema_editor):
    parent = apps.get_model('people', 'Parent')
    parent.objects.update(salary=Ceil(F('salary')))


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_parent_salary'),
    ]

    operations = [
        migrations.RunPython(round_up, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.IntegerField(max_length=8),
        ),
    ]
